[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = true
decorations = "full"
title = "Alacritty@CachyOS"
opacity = 1
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

# [colors.primary]
# background = "0x2E3440"
# foreground = "0xD8DEE9"
#
# [colors.normal]
# black = "0x3B4252"
# red = "0xBF616A"
# green = "0xA3BE8C"
# yellow = "0xEBCB8B"
# blue = "0x81A1C1"
# magenta = "0xB48EAD"
# cyan = "0x88C0D0"
# white = "0xE5E9F0"
#
# [colors.bright]
# black = "0x4C566A"
# red = "0xBF616A"
# green = "0xA3BE8C"
# yellow = "0xEBCB8B"
# blue = "0x81A1C1"
# magenta = "0xB48EAD"
# cyan = "0x8FBCBB"
# white = "0xECEFF4"


# Colors (Gotham)

# Default colors
[colors.primary]
background = '#0a0f14'
foreground = '#98d1ce'

# Normal colors
[colors.normal]
black = '#0a0f14'
red = '#c33027'
green = '#26a98b'
yellow = '#edb54b'
blue = '#195465'
magenta = '#4e5165'
cyan = '#33859d'
white = '#98d1ce'

# Bright colors
[colors.bright]
black = '#10151b'
red = '#d26939'
green = '#081f2d'
yellow = '#245361'
blue = '#093748'
magenta = '#888ba5'
cyan = '#599caa'
white = '#d3ebe9'

[font]
size = 12

[font.normal]
family = "monospace"
style = "Regular"

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Block"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.2

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Right"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[general]
live_config_reload = true
working_directory = "None"
